spring:
  application:
    name: blogger-box-backend
    jackson:
      serialization:
        write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://db.cvltyrqhmqijupkvkqfd.supabase.co:5432/postgres
    username: postgres
    password: "hm9FJvnW*E5sm?b"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update       # update pour dev, validate ou none en prod
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true